# Generated by Django 5.0.3 on 2024-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age_group",
            field=models.CharField(default="young", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="test-man", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="residence_area",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
    ]
