# Generated by Django 5.0.3 on 2024-05-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_age_group_customuser_is_subscribed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='residence_area',
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
