# Generated by Django 5.0.3 on 2024-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
