# Generated by Django 5.0.3 on 2024-05-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='概要')),
                ('content', models.TextField(verbose_name='本文')),
                ('image_url', models.CharField(max_length=255, verbose_name='画像URL')),
                ('is_large', models.BooleanField(default=False, verbose_name='大記事')),
                ('gernre', models.CharField(max_length=255, verbose_name='ジャンル')),
            ],
            options={
                'verbose_name': 'ニュース記事',
                'verbose_name_plural': 'ニュース記事',
                'db_table': 'article',
            },
        ),
    ]
