# Generated by Django 5.0.3 on 2024-03-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Renntermine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("location", models.CharField(max_length=20, verbose_name="場所")),
                ("number", models.IntegerField(verbose_name="番号")),
                ("title", models.CharField(max_length=40, verbose_name="レース名")),
                ("start", models.CharField(max_length=10, verbose_name="発走時刻")),
                ("distance", models.CharField(max_length=10, verbose_name="距離")),
                ("categorie", models.CharField(max_length=10, verbose_name="クラス")),
                ("starters", models.IntegerField(verbose_name="頭数")),
                (
                    "race_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="レースID"
                    ),
                ),
            ],
            options={
                "verbose_name": "開催レース一覧",
                "verbose_name_plural": "開催レース一覧",
                "db_table": "renntermine",
            },
        ),
        migrations.CreateModel(
            name="Starter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=2, verbose_name="馬番")),
                ("name", models.CharField(max_length=20, verbose_name="馬名")),
                ("gag", models.CharField(max_length=10, verbose_name="GAG")),
                ("box", models.CharField(max_length=2, verbose_name="枠番")),
                ("alter", models.CharField(max_length=2, verbose_name="馬齢")),
                ("owner", models.CharField(max_length=20, verbose_name="オーナー")),
                ("trainer", models.CharField(max_length=20, verbose_name="トレーナー")),
                ("jocky", models.CharField(max_length=20, verbose_name="ジョッキー")),
                ("gew", models.CharField(max_length=10, verbose_name="斤量")),
                (
                    "race_id",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="レースID"
                    ),
                ),
            ],
            options={
                "verbose_name": "出走馬一覧",
                "verbose_name_plural": "出走馬一覧",
                "db_table": "starter",
            },
        ),
    ]
