# Generated by Django 5.0.3 on 2024-03-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renntermine",
            name="categorie",
            field=models.CharField(max_length=100, verbose_name="クラス"),
        ),
        migrations.AlterField(
            model_name="renntermine",
            name="title",
            field=models.CharField(max_length=100, verbose_name="レース名"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="jocky",
            field=models.CharField(max_length=50, verbose_name="ジョッキー"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="owner",
            field=models.CharField(max_length=50, verbose_name="オーナー"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="trainer",
            field=models.CharField(max_length=50, verbose_name="トレーナー"),
        ),
    ]
