# Generated by Django 5.0.3 on 2024-03-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "starter",
            "0002_alter_renntermine_categorie_alter_renntermine_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="starter",
            name="race_id",
            field=models.CharField(max_length=10, verbose_name="レースID"),
        ),
    ]
