# Generated by Django 5.0.3 on 2024-03-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starter", "0003_alter_starter_race_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starter",
            name="name",
            field=models.CharField(max_length=50, verbose_name="馬名"),
        ),
    ]
