# Generated by Django 5.0.3 on 2024-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starter", "0005_alter_starter_gew"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starter",
            name="number",
            field=models.CharField(max_length=20, verbose_name="馬番"),
        ),
    ]
