# Generated by Django 5.0.3 on 2024-03-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starter", "0006_alter_starter_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="renntermine",
            name="categorie",
            field=models.CharField(max_length=255, verbose_name="クラス"),
        ),
        migrations.AlterField(
            model_name="renntermine",
            name="distance",
            field=models.CharField(max_length=255, verbose_name="距離"),
        ),
        migrations.AlterField(
            model_name="renntermine",
            name="location",
            field=models.CharField(max_length=255, verbose_name="場所"),
        ),
        migrations.AlterField(
            model_name="renntermine",
            name="race_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="レースID"
            ),
        ),
        migrations.AlterField(
            model_name="renntermine",
            name="start",
            field=models.CharField(max_length=255, verbose_name="発走時刻"),
        ),
        migrations.AlterField(
            model_name="renntermine",
            name="title",
            field=models.CharField(max_length=1255, verbose_name="レース名"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="alter",
            field=models.CharField(max_length=255, verbose_name="馬齢"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="box",
            field=models.CharField(max_length=255, verbose_name="枠番"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="gag",
            field=models.CharField(max_length=255, verbose_name="GAG"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="gew",
            field=models.CharField(max_length=255, verbose_name="斤量"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="jocky",
            field=models.CharField(max_length=255, verbose_name="ジョッキー"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="name",
            field=models.CharField(max_length=255, verbose_name="馬名"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="number",
            field=models.CharField(max_length=255, verbose_name="馬番"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="owner",
            field=models.CharField(max_length=255, verbose_name="オーナー"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="race_id",
            field=models.CharField(max_length=255, verbose_name="レースID"),
        ),
        migrations.AlterField(
            model_name="starter",
            name="trainer",
            field=models.CharField(max_length=255, verbose_name="トレーナー"),
        ),
    ]
