# Generated by Django 5.0.3 on 2024-03-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starter", "0008_alter_renntermine_categorie_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="renntermine",
            name="id",
        ),
        migrations.AlterField(
            model_name="renntermine",
            name="race_id",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="レースID",
            ),
        ),
    ]
