# Generated by Django 5.0.3 on 2024-04-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starter", "0009_remove_renntermine_id_alter_renntermine_race_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="starter",
            name="horse_id",
            field=models.CharField(default=555, max_length=20, verbose_name="馬ID"),
            preserve_default=False,
        ),
    ]
