# Generated by Django 5.0.3 on 2024-04-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("starter", "0011_horsepedigree_horseprofi"),
    ]

    operations = [
        migrations.CreateModel(
            name="KalenderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("rennort", models.CharField(max_length=50)),
                ("renntitel", models.CharField(max_length=100)),
                ("distanz", models.CharField(max_length=20)),
                ("kategorie", models.CharField(max_length=100)),
                ("stute", models.CharField(max_length=20)),
                ("preisgeld", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "重賞日程",
                "verbose_name_plural": "重賞日程",
                "db_table": "rennkalender",
            },
        ),
    ]
