# Generated by Django 5.0.3 on 2024-06-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0012_kalendermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayErgebnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=255)),
                ('platz', models.CharField(max_length=255)),
                ('quote', models.CharField(max_length=255)),
                ('horse_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '当日レース結果',
                'verbose_name_plural': '当日レース結果',
                'db_table': 'TodayErgebnis',
            },
        ),
        migrations.CreateModel(
            name='TodayOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=255)),
                ('quote', models.CharField(max_length=255)),
                ('horse_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '当日オッズ',
                'verbose_name_plural': '当日オッズ',
                'db_table': 'TodayOdds',
            },
        ),
    ]
