# Generated by Django 5.0.3 on 2024-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0013_todayergebnis_todayodds'),
    ]

    operations = [
        migrations.AddField(
            model_name='starter',
            name='equip',
            field=models.CharField(default='aaa', max_length=40, verbose_name='馬具'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starter',
            name='erlbnis',
            field=models.CharField(default='sss', max_length=30, verbose_name='減量'),
            preserve_default=False,
        ),
    ]
