# Generated by Django 5.0.3 on 2024-06-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0014_starter_equip_starter_erlbnis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starter',
            name='equip',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='馬具'),
        ),
        migrations.AlterField(
            model_name='starter',
            name='erlbnis',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='減量'),
        ),
    ]
